version: 0.2

phases:
  pre_build:
    commands:
      - echo "Prepare any needed operations..."
  build:
    commands:
      - echo "No build steps required for static content."
  post_build:
    commands:
      - echo "Post-build operations if any..."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: '.'  # Adjust if your files are in a specific directory


